skip_tags: true

image: Visual Studio 2017

clone_depth: 1

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

branches:
  only:
    - live

install:
  - cinst docfx
  - cinst wkhtmltopdf

build_script:
  - docfx

artifacts:
  - path: '**\*.pdf'

deploy_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email %GITHUB_EMAIL%
  - git config --global user.name "Blazor doc agent"
  - bash releaseDocs.sh
